import { expect, test } from "bun:test";
import { PAGE_TOKEN } from "../helpers/pagination";
import type { Front } from "../../src/front";
import type { operationRoutes } from "../../src/gen/operation-routes.gen";
import type { OperationResponse } from "../../src/operation";
import { createMockClient, jsonResponse } from "../helpers/setup";

type EndpointResponse =
  | {
      [Name in keyof typeof operationRoutes]: OperationResponse<Name>;
    }[keyof typeof operationRoutes]
  | Response;

interface EndpointCase {
  name: string;
  call: (front: Front) => Promise<EndpointResponse>;
  method: string;
  path: string;
  body?: unknown;
  status: number;
  response?: unknown;
  raw?: boolean;
}

const cases: EndpointCase[] = [
  {
    call: (front) =>
      front.accounts.list({
        limit: 1,
        page_token: PAGE_TOKEN,
        sort_by: "created_at",
        sort_order: "asc",
      }),
    method: "GET",
    name: "accounts.list",
    path: `/accounts?limit=1&page_token=${PAGE_TOKEN}&sort_by=created_at&sort_order=asc`,
    response: { _results: [] },
    status: 200,
  },
  {
    body: {},
    call: (front) => front.accounts.create({}),
    method: "POST",
    name: "accounts.create",
    path: "/accounts",
    response: {
      _links: {},
      custom_fields: {},
      description: "Example",
      domains: ["Example"],
      external_id: "customer-123",
      id: "acc_123",
      logo_url: "Example",
      name: "Example",
    },
    status: 201,
  },
  {
    call: (front) => front.accounts.get("acc_123"),
    method: "GET",
    name: "accounts.get",
    path: "/accounts/acc_123",
    response: {
      _links: {},
      custom_fields: {},
      description: "Example",
      domains: ["Example"],
      external_id: "customer-123",
      id: "acc_123",
      logo_url: "Example",
      name: "Example",
    },
    status: 200,
  },
  {
    body: {},
    call: (front) => front.accounts.update("acc_123", {}),
    method: "PATCH",
    name: "accounts.update",
    path: "/accounts/acc_123",
    response: {
      _links: {},
      custom_fields: {},
      description: "Example",
      domains: ["Example"],
      external_id: "customer-123",
      id: "acc_123",
      logo_url: "Example",
      name: "Example",
    },
    status: 200,
  },
  {
    call: (front) => front.accounts.delete("acc_123"),
    method: "DELETE",
    name: "accounts.delete",
    path: "/accounts/acc_123",
    status: 204,
  },
  {
    call: (front) =>
      front.accounts.listContacts("acc_123", {
        limit: 1,
        page_token: PAGE_TOKEN,
        sort_by: "created_at",
        sort_order: "asc",
      }),
    method: "GET",
    name: "accounts.listContacts",
    path: `/accounts/acc_123/contacts?limit=1&page_token=${PAGE_TOKEN}&sort_by=created_at&sort_order=asc`,
    response: { _results: [] },
    status: 200,
  },
  {
    body: { contact_ids: ["ctc_123"] },
    call: (front) => front.accounts.addContacts("acc_123", { contact_ids: ["ctc_123"] }),
    method: "POST",
    name: "accounts.addContacts",
    path: "/accounts/acc_123/contacts",
    status: 204,
  },
  {
    body: { contact_ids: ["ctc_123"] },
    call: (front) => front.accounts.removeContacts("acc_123", { contact_ids: ["ctc_123"] }),
    method: "DELETE",
    name: "accounts.removeContacts",
    path: "/accounts/acc_123/contacts",
    status: 204,
  },
  {
    call: (front) => front.accounts.listCustomFields(),
    method: "GET",
    name: "accounts.listCustomFields",
    path: "/accounts/custom_fields",
    response: { _results: [] },
    status: 200,
  },
  {
    body: { columns: ["Message ID"], end: 100, start: 0, type: "messages" },
    call: (front) =>
      front.analytics.createExport({
        columns: ["Message ID"],
        end: 100,
        start: 0,
        type: "messages",
      }),
    method: "POST",
    name: "analytics.createExport",
    path: "/analytics/exports",
    response: {
      _links: {},
      filters: { tag_ids: ["tag_123"] },
      id: "exp_123",
      progress: 1,
      status: "running",
    },
    status: 201,
  },
  {
    call: (front) => front.analytics.getExport("exp_123"),
    method: "GET",
    name: "analytics.getExport",
    path: "/analytics/exports/exp_123",
    response: {
      _links: {},
      filters: { tag_ids: ["tag_123"] },
      id: "exp_123",
      progress: 1,
      status: "running",
    },
    status: 200,
  },
  {
    body: { end: 1, metrics: ["avg_csat_survey_response"], start: 1 },
    call: (front) =>
      front.analytics.createReport({ end: 1, metrics: ["avg_csat_survey_response"], start: 1 }),
    method: "POST",
    name: "analytics.createReport",
    path: "/analytics/reports",
    response: {
      _links: {},
      metrics: [{ id: "avg_csat_survey_response", type: "number", value: 1 }],
      progress: 1,
      status: "running",
      uid: "Example",
    },
    status: 201,
  },
  {
    call: (front) => front.analytics.getReport("report-uid"),
    method: "GET",
    name: "analytics.getReport",
    path: "/analytics/reports/report-uid",
    response: {
      _links: {},
      metrics: [{ id: "avg_csat_survey_response", type: "number", value: 1 }],
      progress: 1,
      status: "running",
      uid: "Example",
    },
    status: 200,
  },
  {
    body: { app_object: {}, event_type: "Example" },
    call: (front) =>
      front.applications.triggerEvent("application-uid", { app_object: {}, event_type: "Example" }),
    method: "POST",
    name: "applications.triggerEvent",
    path: "/applications/application-uid/events",
    status: 204,
  },
  {
    call: (front) => front.comments.get("com_123"),
    method: "GET",
    name: "comments.get",
    path: "/comments/com_123",
    response: {
      _links: {},
      attachments: [
        {
          content_type: "Example",
          filename: "Example",
          id: "com_123",
          metadata: {},
          size: 1,
          url: "Example",
        },
      ],
      author: {
        _links: {},
        custom_fields: {},
        email: "person@example.com",
        first_name: "Example",
        id: "tea_123",
        is_admin: false,
        is_available: false,
        is_blocked: false,
        last_name: "Example",
        type: "user",
        username: "Example",
      },
      body: "Example",
      id: "com_123",
      is_pinned: false,
    },
    status: 200,
  },
  {
    body: {},
    call: (front) => front.comments.update("com_123", {}),
    method: "PATCH",
    name: "comments.update",
    path: "/comments/com_123",
    response: {
      _links: {},
      attachments: [
        {
          content_type: "Example",
          filename: "Example",
          id: "com_123",
          metadata: {},
          size: 1,
          url: "Example",
        },
      ],
      author: {
        _links: {},
        custom_fields: {},
        email: "person@example.com",
        first_name: "Example",
        id: "tea_123",
        is_admin: false,
        is_available: false,
        is_blocked: false,
        last_name: "Example",
        type: "user",
        username: "Example",
      },
      body: "Example",
      id: "com_123",
      is_pinned: false,
    },
    status: 200,
  },
  {
    call: (front) => front.comments.listMentions("com_123"),
    method: "GET",
    name: "comments.listMentions",
    path: "/comments/com_123/mentions",
    response: { _results: [] },
    status: 200,
  },
  {
    body: { body: "Example" },
    call: (front) => front.comments.addReply("com_123", { body: "Example" }),
    method: "POST",
    name: "comments.addReply",
    path: "/comments/com_123/replies",
    response: {
      _links: {},
      attachments: [
        {
          content_type: "Example",
          filename: "Example",
          id: "com_123",
          metadata: {},
          size: 1,
          url: "Example",
        },
      ],
      author: {
        _links: {},
        custom_fields: {},
        email: "person@example.com",
        first_name: "Example",
        id: "tea_123",
        is_admin: false,
        is_available: false,
        is_blocked: false,
        last_name: "Example",
        type: "user",
        username: "Example",
      },
      body: "Example",
      id: "com_123",
      is_pinned: false,
    },
    status: 201,
  },
  {
    call: (front) => front.comments.downloadAttachment("com_123", "att_123"),
    method: "GET",
    name: "comments.downloadAttachment",
    path: "/comments/com_123/download/att_123",
    raw: true,
    status: 200,
  },
  {
    call: (front) => front.contactLists.list(),
    method: "GET",
    name: "contactLists.list",
    path: "/contact_lists",
    response: { _results: [] },
    status: 200,
  },
  {
    body: { name: "Example" },
    call: (front) => front.contactLists.create({ name: "Example" }),
    method: "POST",
    name: "contactLists.create",
    path: "/contact_lists",
    status: 204,
  },
  {
    call: (front) => front.contactLists.delete("ctl_123"),
    method: "DELETE",
    name: "contactLists.delete",
    path: "/contact_lists/ctl_123",
    status: 204,
  },
  {
    call: (front) =>
      front.contactLists.listContacts("ctl_123", { limit: 1, page_token: PAGE_TOKEN }),
    method: "GET",
    name: "contactLists.listContacts",
    path: `/contact_lists/ctl_123/contacts?limit=1&page_token=${PAGE_TOKEN}`,
    response: { _results: [] },
    status: 200,
  },
  {
    body: { contact_ids: ["ctc_123"] },
    call: (front) => front.contactLists.addContacts("ctl_123", { contact_ids: ["ctc_123"] }),
    method: "POST",
    name: "contactLists.addContacts",
    path: "/contact_lists/ctl_123/contacts",
    status: 204,
  },
  {
    body: { contact_ids: ["ctc_123"] },
    call: (front) => front.contactLists.removeContacts("ctl_123", { contact_ids: ["ctc_123"] }),
    method: "DELETE",
    name: "contactLists.removeContacts",
    path: "/contact_lists/ctl_123/contacts",
    status: 204,
  },
  {
    call: (front) =>
      front.contacts.list({
        limit: 1,
        page_token: PAGE_TOKEN,
        q: "Example",
        sort_by: "created_at",
        sort_order: "asc",
      }),
    method: "GET",
    name: "contacts.list",
    path: `/contacts?limit=1&page_token=${PAGE_TOKEN}&q=Example&sort_by=created_at&sort_order=asc`,
    response: { _results: [] },
    status: 200,
  },
  {
    body: { handles: [{ handle: "person@example.com", source: "email" }] },
    call: (front) =>
      front.contacts.create({ handles: [{ handle: "person@example.com", source: "email" }] }),
    method: "POST",
    name: "contacts.create",
    path: "/contacts",
    response: {},
    status: 201,
  },
  {
    call: (front) => front.contacts.get("ctc_123"),
    method: "GET",
    name: "contacts.get",
    path: "/contacts/ctc_123",
    response: {},
    status: 200,
  },
  {
    body: {},
    call: (front) => front.contacts.update("ctc_123", {}),
    method: "PATCH",
    name: "contacts.update",
    path: "/contacts/ctc_123",
    status: 204,
  },
  {
    call: (front) => front.contacts.delete("ctc_123"),
    method: "DELETE",
    name: "contacts.delete",
    path: "/contacts/ctc_123",
    status: 204,
  },
  {
    call: (front) => front.contacts.listCustomFields(),
    method: "GET",
    name: "contacts.listCustomFields",
    path: "/contacts/custom_fields",
    response: { _results: [] },
    status: 200,
  },
  {
    body: { contact_ids: ["ctc_123"] },
    call: (front) => front.contacts.merge({ contact_ids: ["ctc_123"] }),
    method: "POST",
    name: "contacts.merge",
    path: "/contacts/merge",
    response: {},
    status: 200,
  },
  {
    call: (front) =>
      front.contacts.listConversations("ctc_123", {
        limit: 1,
        page_token: PAGE_TOKEN,
        q: "Example",
      }),
    method: "GET",
    name: "contacts.listConversations",
    path: `/contacts/ctc_123/conversations?limit=1&page_token=${PAGE_TOKEN}&q=Example`,
    response: { _results: [] },
    status: 200,
  },
  {
    body: { handle: "person@example.com", source: "twitter" },
    call: (front) =>
      front.contacts.addHandle("ctc_123", { handle: "person@example.com", source: "twitter" }),
    method: "POST",
    name: "contacts.addHandle",
    path: "/contacts/ctc_123/handles",
    status: 204,
  },
  {
    body: { force: false, handle: "person@example.com", source: "twitter" },
    call: (front) =>
      front.contacts.deleteHandle("ctc_123", {
        force: false,
        handle: "person@example.com",
        source: "twitter",
      }),
    method: "DELETE",
    name: "contacts.deleteHandle",
    path: "/contacts/ctc_123/handles",
    status: 204,
  },
  {
    call: (front) => front.contacts.listNotes("ctc_123"),
    method: "GET",
    name: "contacts.listNotes",
    path: "/contacts/ctc_123/notes",
    response: { _results: [] },
    status: 202,
  },
  {
    body: { author_id: "ctc_123", body: "Example" },
    call: (front) => front.contacts.addNote("ctc_123", { author_id: "ctc_123", body: "Example" }),
    method: "POST",
    name: "contacts.addNote",
    path: "/contacts/ctc_123/notes",
    response: {
      _links: {},
      author: {
        _links: {},
        custom_fields: {},
        email: "person@example.com",
        first_name: "Example",
        id: "tea_123",
        is_admin: false,
        is_available: false,
        is_blocked: false,
        last_name: "Example",
        type: "user",
        username: "Example",
      },
      body: "Example",
    },
    status: 201,
  },
  {
    call: (front) =>
      front.conversations.list({
        limit: 1,
        page_token: PAGE_TOKEN,
        q: "Example",
        sort_by: "created_at",
        sort_order: "asc",
      }),
    method: "GET",
    name: "conversations.list",
    path: `/conversations?limit=1&page_token=${PAGE_TOKEN}&q=Example&sort_by=created_at&sort_order=asc`,
    response: { _results: [] },
    status: 200,
  },
  {
    body: { subject: "Example", type: "discussion" },
    call: (front) => front.conversations.create({ subject: "Example", type: "discussion" }),
    method: "POST",
    name: "conversations.create",
    path: "/conversations",
    response: {
      _links: {},
      assignee: {
        _links: {},
        custom_fields: {},
        email: "person@example.com",
        first_name: "Example",
        id: "tea_123",
        is_admin: false,
        is_available: false,
        is_blocked: false,
        last_name: "Example",
        type: "user",
        username: "Example",
      },
      custom_fields: {},
      id: "cnv_123",
      is_private: false,
      links: [
        {
          _links: {},
          custom_fields: {},
          external_url: "Example",
          id: "cnv_123",
          name: "Example",
          type: "email",
        },
      ],
      metadata: {},
      recipient: { _links: {}, handle: "person@example.com", name: "Example", role: "from" },
      scheduled_reminders: [{ _links: {} }],
      status: "archived",
      subject: "Example",
      tags: [
        {
          _links: {},
          description: "Example",
          highlight: "Example",
          id: "cnv_123",
          is_private: false,
          is_visible_in_conversation_lists: false,
          name: "Example",
        },
      ],
      ticket_ids: ["cnv_123"],
      type: "conversation",
    },
    status: 201,
  },
  {
    call: (front) => front.conversations.get("cnv_123"),
    method: "GET",
    name: "conversations.get",
    path: "/conversations/cnv_123",
    response: {
      _links: {},
      assignee: {
        _links: {},
        custom_fields: {},
        email: "person@example.com",
        first_name: "Example",
        id: "tea_123",
        is_admin: false,
        is_available: false,
        is_blocked: false,
        last_name: "Example",
        type: "user",
        username: "Example",
      },
      custom_fields: {},
      id: "cnv_123",
      is_private: false,
      links: [
        {
          _links: {},
          custom_fields: {},
          external_url: "Example",
          id: "cnv_123",
          name: "Example",
          type: "email",
        },
      ],
      metadata: {},
      recipient: { _links: {}, handle: "person@example.com", name: "Example", role: "from" },
      scheduled_reminders: [{ _links: {} }],
      status: "archived",
      subject: "Example",
      tags: [
        {
          _links: {},
          description: "Example",
          highlight: "Example",
          id: "cnv_123",
          is_private: false,
          is_visible_in_conversation_lists: false,
          name: "Example",
        },
      ],
      ticket_ids: ["cnv_123"],
      type: "conversation",
    },
    status: 200,
  },
  {
    body: {},
    call: (front) => front.conversations.update("cnv_123", {}),
    method: "PATCH",
    name: "conversations.update",
    path: "/conversations/cnv_123",
    status: 204,
  },
  {
    call: (front) => front.conversations.delete("cnv_123"),
    method: "DELETE",
    name: "conversations.delete",
    path: "/conversations/cnv_123",
    status: 204,
  },
  {
    call: (front) => front.conversations.listCustomFields(),
    method: "GET",
    name: "conversations.listCustomFields",
    path: "/conversations/custom_fields",
    response: { _results: [] },
    status: 200,
  },
  {
    call: (front) =>
      front.conversations.search("open priority", { limit: 1, page_token: PAGE_TOKEN }),
    method: "GET",
    name: "conversations.search",
    path: `/conversations/search/open%20priority?limit=1&page_token=${PAGE_TOKEN}`,
    response: { _results: [] },
    status: 200,
  },
  {
    body: { assignee_id: "cnv_123" },
    call: (front) => front.conversations.updateAssignee("cnv_123", { assignee_id: "cnv_123" }),
    method: "PUT",
    name: "conversations.updateAssignee",
    path: "/conversations/cnv_123/assignee",
    status: 204,
  },
  {
    call: (front) => front.conversations.listComments("cnv_123"),
    method: "GET",
    name: "conversations.listComments",
    path: "/conversations/cnv_123/comments",
    response: { _results: [] },
    status: 200,
  },
  {
    body: { body: "Example" },
    call: (front) => front.conversations.addComment("cnv_123", { body: "Example" }),
    method: "POST",
    name: "conversations.addComment",
    path: "/conversations/cnv_123/comments",
    response: {
      _links: {},
      attachments: [
        {
          content_type: "Example",
          filename: "Example",
          id: "com_123",
          metadata: {},
          size: 1,
          url: "Example",
        },
      ],
      author: {
        _links: {},
        custom_fields: {},
        email: "person@example.com",
        first_name: "Example",
        id: "tea_123",
        is_admin: false,
        is_available: false,
        is_blocked: false,
        last_name: "Example",
        type: "user",
        username: "Example",
      },
      body: "Example",
      id: "com_123",
      is_pinned: false,
    },
    status: 201,
  },
  {
    call: (front) => front.conversations.listDrafts("cnv_123"),
    method: "GET",
    name: "conversations.listDrafts",
    path: "/conversations/cnv_123/drafts",
    response: { _results: [] },
    status: 200,
  },
  {
    body: { body: "Example", channel_id: "cha_123", mode: "shared" },
    call: (front) =>
      front.conversations.createDraftReply("cnv_123", {
        body: "Example",
        channel_id: "cha_123",
        mode: "shared",
      }),
    method: "POST",
    name: "conversations.createDraftReply",
    path: "/conversations/cnv_123/drafts",
    response: {},
    status: 200,
  },
  {
    call: (front) =>
      front.conversations.listEvents("cnv_123", { limit: 1, page_token: PAGE_TOKEN }),
    method: "GET",
    name: "conversations.listEvents",
    path: `/conversations/cnv_123/events?limit=1&page_token=${PAGE_TOKEN}`,
    response: { _results: [] },
    status: 200,
  },
  {
    call: (front) => front.conversations.listFollowers("cnv_123"),
    method: "GET",
    name: "conversations.listFollowers",
    path: "/conversations/cnv_123/followers",
    response: { _results: [] },
    status: 200,
  },
  {
    body: { teammate_ids: ["tea_123"] },
    call: (front) =>
      front.conversations.addFollowers(
        "cnv_123",
        { teammate_ids: ["tea_123"] },
        { ignore_errors: false },
      ),
    method: "POST",
    name: "conversations.addFollowers",
    path: "/conversations/cnv_123/followers?ignore_errors=false",
    status: 204,
  },
  {
    body: { teammate_ids: ["tea_123"] },
    call: (front) => front.conversations.deleteFollowers("cnv_123", { teammate_ids: ["tea_123"] }),
    method: "DELETE",
    name: "conversations.deleteFollowers",
    path: "/conversations/cnv_123/followers",
    status: 204,
  },
  {
    call: (front) => front.conversations.listInboxes("cnv_123"),
    method: "GET",
    name: "conversations.listInboxes",
    path: "/conversations/cnv_123/inboxes",
    response: { _results: [] },
    status: 200,
  },
  {
    body: {},
    call: (front) => front.conversations.addLink("cnv_123", {}),
    method: "POST",
    name: "conversations.addLink",
    path: "/conversations/cnv_123/links",
    status: 204,
  },
  {
    body: { link_ids: ["lnk_123"] },
    call: (front) => front.conversations.removeLinks("cnv_123", { link_ids: ["lnk_123"] }),
    method: "DELETE",
    name: "conversations.removeLinks",
    path: "/conversations/cnv_123/links",
    status: 204,
  },
  {
    call: (front) =>
      front.conversations.listMessages("cnv_123", {
        limit: 1,
        page_token: PAGE_TOKEN,
        sort_by: "created_at",
        sort_order: "asc",
      }),
    method: "GET",
    name: "conversations.listMessages",
    path: `/conversations/cnv_123/messages?limit=1&page_token=${PAGE_TOKEN}&sort_by=created_at&sort_order=asc`,
    response: { _results: [] },
    status: 200,
  },
  {
    body: { body: "Example" },
    call: (front) => front.conversations.createMessageReply("cnv_123", { body: "Example" }),
    method: "POST",
    name: "conversations.createMessageReply",
    path: "/conversations/cnv_123/messages",
    response: {},
    status: 202,
  },
  {
    body: { scheduled_at: 1, teammate_id: "tea_123" },
    call: (front) =>
      front.conversations.updateReminders("cnv_123", { scheduled_at: 1, teammate_id: "tea_123" }),
    method: "PATCH",
    name: "conversations.updateReminders",
    path: "/conversations/cnv_123/reminders",
    status: 204,
  },
  {
    body: { tag_ids: ["tag_123"] },
    call: (front) => front.conversations.addTag("cnv_123", { tag_ids: ["tag_123"] }),
    method: "POST",
    name: "conversations.addTag",
    path: "/conversations/cnv_123/tags",
    status: 204,
  },
  {
    body: { tag_ids: ["tag_123"] },
    call: (front) => front.conversations.removeTag("cnv_123", { tag_ids: ["tag_123"] }),
    method: "DELETE",
    name: "conversations.removeTag",
    path: "/conversations/cnv_123/tags",
    status: 204,
  },
  {
    call: (front) => front.downloads.download("att_123"),
    method: "GET",
    name: "downloads.download",
    path: "/download/att_123",
    raw: true,
    status: 200,
  },
  {
    body: { version: "Example" },
    call: (front) => front.drafts.delete("msg_123", { version: "Example" }),
    method: "DELETE",
    name: "drafts.delete",
    path: "/drafts/msg_123",
    status: 204,
  },
  {
    body: { body: "Example", channel_id: "cha_123", mode: "shared" },
    call: (front) =>
      front.drafts.edit("msg_123", { body: "Example", channel_id: "cha_123", mode: "shared" }),
    method: "PATCH",
    name: "drafts.edit",
    path: "/drafts/msg_123",
    response: {},
    status: 200,
  },
  {
    call: (front) =>
      front.events.list({
        limit: 1,
        page_token: PAGE_TOKEN,
        q: "Example",
        sort_by: "created_at",
        sort_order: "asc",
      }),
    method: "GET",
    name: "events.list",
    path: `/events?limit=1&page_token=${PAGE_TOKEN}&q=Example&sort_by=created_at&sort_order=asc`,
    response: { _results: [] },
    status: 200,
  },
  {
    call: (front) => front.events.get("evt_123"),
    method: "GET",
    name: "events.get",
    path: "/events/evt_123",
    response: {},
    status: 200,
  },
  {
    call: (front) => front.inboxes.list(),
    method: "GET",
    name: "inboxes.list",
    path: "/inboxes",
    response: { _results: [] },
    status: 200,
  },
  {
    body: { name: "Example" },
    call: (front) => front.inboxes.create({ name: "Example" }),
    method: "POST",
    name: "inboxes.create",
    path: "/inboxes",
    response: {},
    status: 201,
  },
  {
    call: (front) => front.inboxes.get("inb_123"),
    method: "GET",
    name: "inboxes.get",
    path: "/inboxes/inb_123",
    response: {},
    status: 200,
  },
  {
    call: (front) => front.inboxes.listCustomFields(),
    method: "GET",
    name: "inboxes.listCustomFields",
    path: "/inboxes/custom_fields",
    response: { _results: [] },
    status: 200,
  },
  {
    call: (front) => front.inboxes.listChannels("inb_123"),
    method: "GET",
    name: "inboxes.listChannels",
    path: "/inboxes/inb_123/channels",
    response: { _results: [] },
    status: 200,
  },
  {
    call: (front) =>
      front.inboxes.listConversations("inb_123", {
        limit: 1,
        page_token: PAGE_TOKEN,
        q: "Example",
      }),
    method: "GET",
    name: "inboxes.listConversations",
    path: `/inboxes/inb_123/conversations?limit=1&page_token=${PAGE_TOKEN}&q=Example`,
    response: { _results: [] },
    status: 200,
  },
  {
    body: {
      body: "Example",
      body_format: "markdown",
      created_at: 1,
      external_id: "customer-123",
      metadata: { is_archived: false, is_inbound: false, should_skip_rules: false },
      sender: { handle: "person@example.com" },
      to: ["Example"],
      type: "email",
    },
    call: (front) =>
      front.inboxes.importMessage("inb_123", {
        body: "Example",
        body_format: "markdown",
        created_at: 1,
        external_id: "customer-123",
        metadata: { is_archived: false, is_inbound: false, should_skip_rules: false },
        sender: { handle: "person@example.com" },
        to: ["Example"],
        type: "email",
      }),
    method: "POST",
    name: "inboxes.importMessage",
    path: "/inboxes/inb_123/imported_messages",
    response: {},
    status: 202,
  },
  {
    call: (front) => front.inboxes.listTeammateAccess("inb_123"),
    method: "GET",
    name: "inboxes.listTeammateAccess",
    path: "/inboxes/inb_123/teammates",
    response: { _results: [] },
    status: 200,
  },
  {
    body: { teammate_ids: ["tea_123"] },
    call: (front) => front.inboxes.addTeammateAccess("inb_123", { teammate_ids: ["tea_123"] }),
    method: "POST",
    name: "inboxes.addTeammateAccess",
    path: "/inboxes/inb_123/teammates",
    status: 204,
  },
  {
    body: { teammate_ids: ["tea_123"] },
    call: (front) => front.inboxes.removeTeammateAccess("inb_123", { teammate_ids: ["tea_123"] }),
    method: "DELETE",
    name: "inboxes.removeTeammateAccess",
    path: "/inboxes/inb_123/teammates",
    status: 204,
  },
  {
    call: (front) =>
      front.links.list({
        limit: 1,
        page_token: PAGE_TOKEN,
        q: "Example",
        sort_by: "created_at",
        sort_order: "asc",
      }),
    method: "GET",
    name: "links.list",
    path: `/links?limit=1&page_token=${PAGE_TOKEN}&q=Example&sort_by=created_at&sort_order=asc`,
    response: { _results: [] },
    status: 200,
  },
  {
    body: {},
    call: (front) => front.links.create({}),
    method: "POST",
    name: "links.create",
    path: "/links",
    response: {
      _links: {},
      custom_fields: {},
      external_url: "Example",
      id: "lnk_123",
      name: "Example",
      type: "email",
    },
    status: 201,
  },
  {
    call: (front) => front.links.get("lnk_123"),
    method: "GET",
    name: "links.get",
    path: "/links/lnk_123",
    response: {
      _links: {},
      custom_fields: {},
      external_url: "Example",
      id: "lnk_123",
      name: "Example",
      type: "email",
    },
    status: 200,
  },
  {
    body: {},
    call: (front) => front.links.update("lnk_123", {}),
    method: "PATCH",
    name: "links.update",
    path: "/links/lnk_123",
    status: 204,
  },
  {
    call: (front) => front.links.listCustomFields(),
    method: "GET",
    name: "links.listCustomFields",
    path: "/links/custom_fields",
    response: { _results: [] },
    status: 200,
  },
  {
    call: (front) =>
      front.links.listConversations("lnk_123", {
        limit: 1,
        page_token: PAGE_TOKEN,
        q: "Example",
        sort_by: "created_at",
        sort_order: "asc",
      }),
    method: "GET",
    name: "links.listConversations",
    path: `/links/lnk_123/conversations?limit=1&page_token=${PAGE_TOKEN}&q=Example&sort_by=created_at&sort_order=asc`,
    response: { _results: [] },
    status: 200,
  },
  {
    call: (front) => front.me.details(),
    method: "GET",
    name: "me.details",
    path: "/me",
    response: { _links: {}, id: "cmp_123", name: "Example" },
    status: 200,
  },
  {
    call: (front) =>
      front.messageTemplateFolders.list({ sort_by: "created_at", sort_order: "asc" }),
    method: "GET",
    name: "messageTemplateFolders.list",
    path: "/message_template_folders?sort_by=created_at&sort_order=asc",
    response: { _results: [] },
    status: 200,
  },
  {
    body: { name: "Example" },
    call: (front) => front.messageTemplateFolders.create({ name: "Example" }),
    method: "POST",
    name: "messageTemplateFolders.create",
    path: "/message_template_folders",
    response: { _links: {}, id: "fld_123", name: "Example" },
    status: 201,
  },
  {
    call: (front) => front.messageTemplateFolders.get("fld_123"),
    method: "GET",
    name: "messageTemplateFolders.get",
    path: "/message_template_folders/fld_123",
    response: { _links: {}, id: "fld_123", name: "Example" },
    status: 200,
  },
  {
    body: {},
    call: (front) => front.messageTemplateFolders.update("fld_123", {}),
    method: "PATCH",
    name: "messageTemplateFolders.update",
    path: "/message_template_folders/fld_123",
    response: { _links: {}, id: "fld_123", name: "Example" },
    status: 200,
  },
  {
    call: (front) => front.messageTemplateFolders.delete("fld_123"),
    method: "DELETE",
    name: "messageTemplateFolders.delete",
    path: "/message_template_folders/fld_123",
    response: {},
    status: 202,
  },
  {
    call: (front) => front.messageTemplateFolders.listChildFolders("fld_123"),
    method: "GET",
    name: "messageTemplateFolders.listChildFolders",
    path: "/message_template_folders/fld_123/message_template_folders",
    response: { _results: [] },
    status: 200,
  },
  {
    body: { name: "Example" },
    call: (front) => front.messageTemplateFolders.createChildFolder("fld_123", { name: "Example" }),
    method: "POST",
    name: "messageTemplateFolders.createChildFolder",
    path: "/message_template_folders/fld_123/message_template_folders",
    response: { _links: {}, id: "fld_123", name: "Example" },
    status: 201,
  },
  {
    call: (front) => front.messageTemplateFolders.listChildTemplates("fld_123"),
    method: "GET",
    name: "messageTemplateFolders.listChildTemplates",
    path: "/message_template_folders/fld_123/message_templates",
    response: { _results: [] },
    status: 200,
  },
  {
    body: { body: "Example", name: "Example" },
    call: (front) =>
      front.messageTemplateFolders.createChildTemplate("fld_123", {
        body: "Example",
        name: "Example",
      }),
    method: "POST",
    name: "messageTemplateFolders.createChildTemplate",
    path: "/message_template_folders/fld_123/message_templates",
    response: {
      _links: {},
      attachments: [
        {
          content_type: "Example",
          filename: "Example",
          id: "fld_123",
          metadata: {},
          size: 1,
          url: "Example",
        },
      ],
      body: "Example",
      id: "fld_123",
      inbox_ids: ["inb_123"],
      is_available_for_all_inboxes: false,
      name: "Example",
      subject: "Example",
    },
    status: 201,
  },
  {
    call: (front) => front.messageTemplates.list({ sort_by: "created_at", sort_order: "asc" }),
    method: "GET",
    name: "messageTemplates.list",
    path: "/message_templates?sort_by=created_at&sort_order=asc",
    response: { _results: [] },
    status: 200,
  },
  {
    body: { body: "Example", name: "Example" },
    call: (front) => front.messageTemplates.create({ body: "Example", name: "Example" }),
    method: "POST",
    name: "messageTemplates.create",
    path: "/message_templates",
    response: {
      _links: {},
      attachments: [
        {
          content_type: "Example",
          filename: "Example",
          id: "rsp_123",
          metadata: {},
          size: 1,
          url: "Example",
        },
      ],
      body: "Example",
      id: "rsp_123",
      inbox_ids: ["inb_123"],
      is_available_for_all_inboxes: false,
      name: "Example",
      subject: "Example",
    },
    status: 201,
  },
  {
    call: (front) => front.messageTemplates.get("rsp_123"),
    method: "GET",
    name: "messageTemplates.get",
    path: "/message_templates/rsp_123",
    response: {
      _links: {},
      attachments: [
        {
          content_type: "Example",
          filename: "Example",
          id: "rsp_123",
          metadata: {},
          size: 1,
          url: "Example",
        },
      ],
      body: "Example",
      id: "rsp_123",
      inbox_ids: ["inb_123"],
      is_available_for_all_inboxes: false,
      name: "Example",
      subject: "Example",
    },
    status: 200,
  },
  {
    body: { body: "Updated body" },
    call: (front) => front.messageTemplates.update("rsp_123", { body: "Updated body" }),
    method: "PATCH",
    name: "messageTemplates.update",
    path: "/message_templates/rsp_123",
    response: {
      _links: {},
      attachments: [
        {
          content_type: "Example",
          filename: "Example",
          id: "rsp_123",
          metadata: {},
          size: 1,
          url: "Example",
        },
      ],
      body: "Example",
      id: "rsp_123",
      inbox_ids: ["inb_123"],
      is_available_for_all_inboxes: false,
      name: "Example",
      subject: "Example",
    },
    status: 200,
  },
  {
    call: (front) => front.messageTemplates.delete("rsp_123"),
    method: "DELETE",
    name: "messageTemplates.delete",
    path: "/message_templates/rsp_123",
    status: 204,
  },
  {
    call: (front) => front.messageTemplates.downloadAttachment("rsp_123", "att_123"),
    method: "GET",
    name: "messageTemplates.downloadAttachment",
    path: "/message_templates/rsp_123/download/att_123",
    raw: true,
    status: 200,
  },
  {
    call: (front) => front.messages.get("msg_123"),
    method: "GET",
    name: "messages.get",
    path: "/messages/msg_123",
    response: {},
    status: 200,
  },
  {
    call: (front) => front.messages.fetchRaw("msg_123", { headers: { Accept: "message/rfc822" } }),
    method: "GET",
    name: "messages.fetchRaw",
    path: "/messages/msg_123",
    raw: true,
    status: 200,
  },
  {
    call: (front) => front.messages.downloadAttachment("msg_123", "att_123"),
    method: "GET",
    name: "messages.downloadAttachment",
    path: "/messages/msg_123/download/att_123",
    raw: true,
    status: 200,
  },
  {
    call: (front) => front.messages.getSeen("msg_123"),
    method: "GET",
    name: "messages.getSeen",
    path: "/messages/msg_123/seen",
    response: { _results: [] },
    status: 200,
  },
  {
    body: {},
    call: (front) => front.messages.markSeen("msg_123"),
    method: "POST",
    name: "messages.markSeen",
    path: "/messages/msg_123/seen",
    status: 204,
  },
  {
    call: (front) => front.rules.list(),
    method: "GET",
    name: "rules.list",
    path: "/rules",
    response: { _results: [] },
    status: 200,
  },
  {
    call: (front) => front.rules.get("rul_123"),
    method: "GET",
    name: "rules.get",
    path: "/rules/rul_123",
    response: {
      _links: {},
      actions: ["Example"],
      id: "rul_123",
      is_private: false,
      name: "Example",
    },
    status: 200,
  },
  {
    call: (front) => front.shifts.list(),
    method: "GET",
    name: "shifts.list",
    path: "/shifts",
    response: { _results: [] },
    status: 200,
  },
  {
    body: {
      color: "black",
      name: "Example",
      teammate_ids: ["tea_123"],
      times: {},
      timezone: "Example",
    },
    call: (front) =>
      front.shifts.create({
        color: "black",
        name: "Example",
        teammate_ids: ["tea_123"],
        times: {},
        timezone: "Example",
      }),
    method: "POST",
    name: "shifts.create",
    path: "/shifts",
    response: {
      _links: {},
      color: "black",
      id: "shf_123",
      name: "Example",
      times: {},
      timezone: "Example",
    },
    status: 201,
  },
  {
    call: (front) => front.shifts.get("shf_123"),
    method: "GET",
    name: "shifts.get",
    path: "/shifts/shf_123",
    response: {
      _links: {},
      color: "black",
      id: "shf_123",
      name: "Example",
      times: {},
      timezone: "Example",
    },
    status: 200,
  },
  {
    body: {},
    call: (front) => front.shifts.update("shf_123", {}),
    method: "PATCH",
    name: "shifts.update",
    path: "/shifts/shf_123",
    status: 204,
  },
  {
    call: (front) => front.shifts.listTeammates("shf_123"),
    method: "GET",
    name: "shifts.listTeammates",
    path: "/shifts/shf_123/teammates",
    response: { _results: [] },
    status: 200,
  },
  {
    body: { teammate_ids: ["tea_123"] },
    call: (front) => front.shifts.addTeammates("shf_123", { teammate_ids: ["tea_123"] }),
    method: "POST",
    name: "shifts.addTeammates",
    path: "/shifts/shf_123/teammates",
    status: 204,
  },
  {
    body: { teammate_ids: ["tea_123"] },
    call: (front) => front.shifts.removeTeammates("shf_123", { teammate_ids: ["tea_123"] }),
    method: "DELETE",
    name: "shifts.removeTeammates",
    path: "/shifts/shf_123/teammates",
    status: 204,
  },
  {
    call: (front) => front.signatures.get("sig_123"),
    method: "GET",
    name: "signatures.get",
    path: "/signatures/sig_123",
    response: {
      _links: {},
      body: "Example",
      channel_ids: ["cha_123"],
      id: "sig_123",
      is_default: false,
      is_private: false,
      is_visible_for_all_teammate_channels: false,
      name: "Example",
      sender_info: "Example",
    },
    status: 200,
  },
  {
    body: { is_default: false },
    call: (front) => front.signatures.update("sig_123", { is_default: false }),
    method: "PATCH",
    name: "signatures.update",
    path: "/signatures/sig_123",
    response: {
      _links: {},
      body: "Example",
      channel_ids: ["cha_123"],
      id: "sig_123",
      is_default: false,
      is_private: false,
      is_visible_for_all_teammate_channels: false,
      name: "Example",
      sender_info: "Example",
    },
    status: 200,
  },
  {
    call: (front) => front.signatures.delete("sig_123"),
    method: "DELETE",
    name: "signatures.delete",
    path: "/signatures/sig_123",
    status: 204,
  },
  {
    call: (front) => front.signatures.listTeammate("tea_123"),
    method: "GET",
    name: "signatures.listTeammate",
    path: "/teammates/tea_123/signatures",
    response: { _results: [] },
    status: 200,
  },
  {
    body: { body: "Example", is_default: false, name: "Example" },
    call: (front) =>
      front.signatures.createTeammate("tea_123", {
        body: "Example",
        is_default: false,
        name: "Example",
      }),
    method: "POST",
    name: "signatures.createTeammate",
    path: "/teammates/tea_123/signatures",
    response: {
      _links: {},
      body: "Example",
      channel_ids: ["cha_123"],
      id: "sig_123",
      is_default: false,
      is_private: false,
      is_visible_for_all_teammate_channels: false,
      name: "Example",
      sender_info: "Example",
    },
    status: 201,
  },
  {
    call: (front) => front.signatures.listTeam("tim_123"),
    method: "GET",
    name: "signatures.listTeam",
    path: "/teams/tim_123/signatures",
    response: { _results: [] },
    status: 200,
  },
  {
    body: { body: "Example", is_default: false, name: "Example" },
    call: (front) =>
      front.signatures.createTeam("tim_123", {
        body: "Example",
        is_default: false,
        name: "Example",
      }),
    method: "POST",
    name: "signatures.createTeam",
    path: "/teams/tim_123/signatures",
    response: {
      _links: {},
      body: "Example",
      channel_ids: ["cha_123"],
      id: "sig_123",
      is_default: false,
      is_private: false,
      is_visible_for_all_teammate_channels: false,
      name: "Example",
      sender_info: "Example",
    },
    status: 201,
  },
  {
    call: (front) => front.views.list({ limit: 1, page_token: PAGE_TOKEN }),
    method: "GET",
    name: "views.list",
    path: `/views?limit=1&page_token=${PAGE_TOKEN}`,
    response: { _results: [] },
    status: 200,
  },
  {
    call: (front) => front.views.get("viw_123"),
    method: "GET",
    name: "views.get",
    path: "/views/viw_123",
    response: {
      _links: {},
      assignee_ids: ["viw_123"],
      highlight: "Example",
      id: "viw_123",
      inbox_ids: ["inb_123"],
      name: "Example",
      no_tags: false,
      not_assignee_ids: ["viw_123"],
      not_tag_ids: ["viw_123"],
      tag_ids: ["tag_123"],
    },
    status: 200,
  },
  {
    body: {},
    call: (front) => front.views.update("viw_123", {}),
    method: "PATCH",
    name: "views.update",
    path: "/views/viw_123",
    status: 204,
  },
  {
    body: { teammate_ids: ["tea_123"] },
    call: (front) => front.views.addTeammates("viw_123", { teammate_ids: ["tea_123"] }),
    method: "POST",
    name: "views.addTeammates",
    path: "/views/viw_123/teammates",
    status: 204,
  },
  {
    call: (front) => front.knowledgeBases.list(),
    method: "GET",
    name: "knowledgeBases.list",
    path: "/knowledge_bases",
    response: { _results: [] },
    status: 200,
  },
  {
    body: { name: "Example", type: "internal" },
    call: (front) => front.knowledgeBases.create({ name: "Example", type: "internal" }),
    method: "POST",
    name: "knowledgeBases.create",
    path: "/knowledge_bases",
    response: {
      _links: {},
      id: "knb_123",
      locale: "fr",
      name: "Example",
      status: "published",
      type: "internal",
    },
    status: 201,
  },
  {
    call: (front) => front.knowledgeBases.get("knb_123"),
    method: "GET",
    name: "knowledgeBases.get",
    path: "/knowledge_bases/knb_123",
    response: { _links: {}, id: "knb_123", locales: ["en"], type: "internal" },
    status: 200,
  },
  {
    call: (front) => front.knowledgeBases.getContentDefault("knb_123"),
    method: "GET",
    name: "knowledgeBases.getContentDefault",
    path: "/knowledge_bases/knb_123/content",
    response: {
      _links: {},
      id: "knb_123",
      locale: "fr",
      name: "Example",
      status: "published",
      type: "internal",
    },
    status: 200,
  },
  {
    body: {},
    call: (front) => front.knowledgeBases.updateContentDefault("knb_123", {}),
    method: "PATCH",
    name: "knowledgeBases.updateContentDefault",
    path: "/knowledge_bases/knb_123/content",
    response: {
      _links: {},
      id: "knb_123",
      locale: "fr",
      name: "Example",
      status: "published",
      type: "internal",
    },
    status: 200,
  },
  {
    call: (front) => front.knowledgeBases.getContentLocale("knb_123", "en"),
    method: "GET",
    name: "knowledgeBases.getContentLocale",
    path: "/knowledge_bases/knb_123/locales/en/content",
    response: {
      _links: {},
      id: "knb_123",
      locale: "fr",
      name: "Example",
      status: "published",
      type: "internal",
    },
    status: 200,
  },
  {
    body: {},
    call: (front) => front.knowledgeBases.updateContentLocale("knb_123", "en", {}),
    method: "PATCH",
    name: "knowledgeBases.updateContentLocale",
    path: "/knowledge_bases/knb_123/locales/en/content",
    response: {
      _links: {},
      id: "knb_123",
      locale: "fr",
      name: "Example",
      status: "published",
      type: "internal",
    },
    status: 200,
  },
  {
    call: (front) =>
      front.knowledgeBases.listArticles("knb_123", { limit: 1, page_token: PAGE_TOKEN }),
    method: "GET",
    name: "knowledgeBases.listArticles",
    path: `/knowledge_bases/knb_123/articles?limit=1&page_token=${PAGE_TOKEN}`,
    response: { _results: [] },
    status: 200,
  },
  {
    body: { status: "draft" },
    call: (front) => front.knowledgeBases.createArticleDefault("knb_123", { status: "draft" }),
    method: "POST",
    name: "knowledgeBases.createArticleDefault",
    path: "/knowledge_bases/knb_123/articles",
    response: {
      _links: {},
      attachments: [
        {
          content_type: "Example",
          filename: "Example",
          id: "kba_123",
          metadata: {},
          size: 1,
          url: "Example",
        },
      ],
      content: "Example",
      id: "kba_123",
      keywords: ["Example"],
      locale: "en",
      name: "Example",
      slug: "Example",
      status: "Example",
    },
    status: 201,
  },
  {
    body: { status: "draft" },
    call: (front) => front.knowledgeBases.createArticleLocale("knb_123", "en", { status: "draft" }),
    method: "POST",
    name: "knowledgeBases.createArticleLocale",
    path: "/knowledge_bases/knb_123/locales/en/articles",
    response: {
      _links: {},
      attachments: [
        {
          content_type: "Example",
          filename: "Example",
          id: "kba_123",
          metadata: {},
          size: 1,
          url: "Example",
        },
      ],
      content: "Example",
      id: "kba_123",
      keywords: ["Example"],
      locale: "en",
      name: "Example",
      slug: "Example",
      status: "Example",
    },
    status: 201,
  },
  {
    call: (front) =>
      front.knowledgeBases.listCategories("knb_123", { limit: 1, page_token: PAGE_TOKEN }),
    method: "GET",
    name: "knowledgeBases.listCategories",
    path: `/knowledge_bases/knb_123/categories?limit=1&page_token=${PAGE_TOKEN}`,
    response: { _results: [] },
    status: 200,
  },
  {
    body: { name: "Example" },
    call: (front) => front.knowledgeBases.createCategoryDefault("knb_123", { name: "Example" }),
    method: "POST",
    name: "knowledgeBases.createCategoryDefault",
    path: "/knowledge_bases/knb_123/categories",
    response: {
      _links: {},
      description: "Example",
      id: "kbc_123",
      is_hidden: false,
      locale: "fr",
      name: "Example",
    },
    status: 201,
  },
  {
    body: { name: "Example" },
    call: (front) =>
      front.knowledgeBases.createCategoryLocale("knb_123", "en", { name: "Example" }),
    method: "POST",
    name: "knowledgeBases.createCategoryLocale",
    path: "/knowledge_bases/knb_123/locales/en/categories",
    response: {
      _links: {},
      description: "Example",
      id: "kbc_123",
      is_hidden: false,
      locale: "fr",
      name: "Example",
    },
    status: 201,
  },
  {
    call: (front) => front.knowledgeBaseArticles.get("kba_123"),
    method: "GET",
    name: "knowledgeBaseArticles.get",
    path: "/knowledge_base_articles/kba_123",
    response: { _links: {}, id: "kba_123", locales: ["en"], slug: "Example" },
    status: 200,
  },
  {
    call: (front) => front.knowledgeBaseArticles.delete("kba_123"),
    method: "DELETE",
    name: "knowledgeBaseArticles.delete",
    path: "/knowledge_base_articles/kba_123",
    response: { _links: {}, id: "kba_123", locales: ["en"], slug: "Example" },
    status: 200,
  },
  {
    call: (front) => front.knowledgeBaseArticles.getContentDefault("kba_123"),
    method: "GET",
    name: "knowledgeBaseArticles.getContentDefault",
    path: "/knowledge_base_articles/kba_123/content",
    response: {
      _links: {},
      attachments: [
        {
          content_type: "Example",
          filename: "Example",
          id: "kba_123",
          metadata: {},
          size: 1,
          url: "Example",
        },
      ],
      content: "Example",
      id: "kba_123",
      keywords: ["Example"],
      locale: "en",
      name: "Example",
      slug: "Example",
      status: "Example",
    },
    status: 200,
  },
  {
    body: { status: "draft" },
    call: (front) =>
      front.knowledgeBaseArticles.updateContentDefault("kba_123", { status: "draft" }),
    method: "PATCH",
    name: "knowledgeBaseArticles.updateContentDefault",
    path: "/knowledge_base_articles/kba_123/content",
    response: {
      _links: {},
      attachments: [
        {
          content_type: "Example",
          filename: "Example",
          id: "kba_123",
          metadata: {},
          size: 1,
          url: "Example",
        },
      ],
      content: "Example",
      id: "kba_123",
      keywords: ["Example"],
      locale: "en",
      name: "Example",
      slug: "Example",
      status: "Example",
    },
    status: 200,
  },
  {
    call: (front) => front.knowledgeBaseArticles.getContentLocale("kba_123", "en"),
    method: "GET",
    name: "knowledgeBaseArticles.getContentLocale",
    path: "/knowledge_base_articles/kba_123/locales/en/content",
    response: {
      _links: {},
      attachments: [
        {
          content_type: "Example",
          filename: "Example",
          id: "kba_123",
          metadata: {},
          size: 1,
          url: "Example",
        },
      ],
      content: "Example",
      id: "kba_123",
      keywords: ["Example"],
      locale: "en",
      name: "Example",
      slug: "Example",
      status: "Example",
    },
    status: 200,
  },
  {
    body: { status: "draft" },
    call: (front) =>
      front.knowledgeBaseArticles.updateContentLocale("kba_123", "en", { status: "draft" }),
    method: "PATCH",
    name: "knowledgeBaseArticles.updateContentLocale",
    path: "/knowledge_base_articles/kba_123/locales/en/content",
    response: {
      _links: {},
      attachments: [
        {
          content_type: "Example",
          filename: "Example",
          id: "kba_123",
          metadata: {},
          size: 1,
          url: "Example",
        },
      ],
      content: "Example",
      id: "kba_123",
      keywords: ["Example"],
      locale: "en",
      name: "Example",
      slug: "Example",
      status: "Example",
    },
    status: 200,
  },
  {
    call: (front) => front.knowledgeBaseArticles.downloadAttachment("kba_123", "att_123"),
    method: "GET",
    name: "knowledgeBaseArticles.downloadAttachment",
    path: "/knowledge_base_articles/kba_123/download/att_123",
    raw: true,
    status: 200,
  },
  {
    call: (front) => front.knowledgeBaseCategories.get("kbc_123"),
    method: "GET",
    name: "knowledgeBaseCategories.get",
    path: "/knowledge_base_categories/kbc_123",
    response: { _links: {}, id: "kbc_123", is_hidden: false, locales: ["en"], slug: "Example" },
    status: 200,
  },
  {
    call: (front) => front.knowledgeBaseCategories.delete("kbc_123"),
    method: "DELETE",
    name: "knowledgeBaseCategories.delete",
    path: "/knowledge_base_categories/kbc_123",
    status: 204,
  },
  {
    call: (front) =>
      front.knowledgeBaseCategories.listArticles("kbc_123", { limit: 1, page_token: PAGE_TOKEN }),
    method: "GET",
    name: "knowledgeBaseCategories.listArticles",
    path: `/knowledge_base_categories/kbc_123/articles?limit=1&page_token=${PAGE_TOKEN}`,
    response: { _results: [] },
    status: 200,
  },
  {
    call: (front) => front.knowledgeBaseCategories.getContentDefault("kbc_123"),
    method: "GET",
    name: "knowledgeBaseCategories.getContentDefault",
    path: "/knowledge_base_categories/kbc_123/content",
    response: {
      _links: {},
      description: "Example",
      id: "kbc_123",
      is_hidden: false,
      locale: "fr",
      name: "Example",
    },
    status: 200,
  },
  {
    body: {},
    call: (front) => front.knowledgeBaseCategories.updateContentDefault("kbc_123", {}),
    method: "PATCH",
    name: "knowledgeBaseCategories.updateContentDefault",
    path: "/knowledge_base_categories/kbc_123/content",
    response: {
      _links: {},
      description: "Example",
      id: "kbc_123",
      is_hidden: false,
      locale: "fr",
      name: "Example",
    },
    status: 200,
  },
  {
    call: (front) => front.knowledgeBaseCategories.getContentLocale("kbc_123", "en"),
    method: "GET",
    name: "knowledgeBaseCategories.getContentLocale",
    path: "/knowledge_base_categories/kbc_123/locales/en/content",
    response: {
      _links: {},
      description: "Example",
      id: "kbc_123",
      is_hidden: false,
      locale: "fr",
      name: "Example",
    },
    status: 200,
  },
  {
    body: {},
    call: (front) => front.knowledgeBaseCategories.updateContentLocale("kbc_123", "en", {}),
    method: "PATCH",
    name: "knowledgeBaseCategories.updateContentLocale",
    path: "/knowledge_base_categories/kbc_123/locales/en/content",
    response: {
      _links: {},
      description: "Example",
      id: "kbc_123",
      is_hidden: false,
      locale: "fr",
      name: "Example",
    },
    status: 200,
  },
  {
    call: (front) => front.teammateGroups.list(),
    method: "GET",
    name: "teammateGroups.list",
    path: "/teammate_groups",
    response: { _results: [] },
    status: 200,
  },
  {
    body: { name: "Example" },
    call: (front) => front.teammateGroups.create({ name: "Example" }),
    method: "POST",
    name: "teammateGroups.create",
    path: "/teammate_groups",
    response: {
      _links: {},
      description: "Example",
      id: "tmg_123",
      is_managed_by_scim: false,
      name: "Example",
      permissions: {},
    },
    status: 201,
  },
  {
    call: (front) => front.teammateGroups.get("tmg_123"),
    method: "GET",
    name: "teammateGroups.get",
    path: "/teammate_groups/tmg_123",
    response: {
      _links: {},
      description: "Example",
      id: "tmg_123",
      is_managed_by_scim: false,
      name: "Example",
      permissions: {},
    },
    status: 200,
  },
  {
    body: {},
    call: (front) => front.teammateGroups.update("tmg_123", {}),
    method: "PATCH",
    name: "teammateGroups.update",
    path: "/teammate_groups/tmg_123",
    status: 204,
  },
  {
    call: (front) => front.teammateGroups.delete("tmg_123"),
    method: "DELETE",
    name: "teammateGroups.delete",
    path: "/teammate_groups/tmg_123",
    status: 204,
  },
  {
    call: (front) => front.teammateGroups.listInboxes("tmg_123"),
    method: "GET",
    name: "teammateGroups.listInboxes",
    path: "/teammate_groups/tmg_123/inboxes",
    response: { _results: [] },
    status: 200,
  },
  {
    body: { inbox_ids: ["inb_123"] },
    call: (front) => front.teammateGroups.addInboxes("tmg_123", { inbox_ids: ["inb_123"] }),
    method: "POST",
    name: "teammateGroups.addInboxes",
    path: "/teammate_groups/tmg_123/inboxes",
    status: 204,
  },
  {
    body: { inbox_ids: ["inb_123"] },
    call: (front) => front.teammateGroups.removeInboxes("tmg_123", { inbox_ids: ["inb_123"] }),
    method: "DELETE",
    name: "teammateGroups.removeInboxes",
    path: "/teammate_groups/tmg_123/inboxes",
    status: 204,
  },
  {
    call: (front) => front.teammateGroups.listTeammates("tmg_123"),
    method: "GET",
    name: "teammateGroups.listTeammates",
    path: "/teammate_groups/tmg_123/teammates",
    response: { _results: [] },
    status: 200,
  },
  {
    body: { teammate_ids: ["tea_123"] },
    call: (front) => front.teammateGroups.addTeammates("tmg_123", { teammate_ids: ["tea_123"] }),
    method: "POST",
    name: "teammateGroups.addTeammates",
    path: "/teammate_groups/tmg_123/teammates",
    status: 204,
  },
  {
    body: { teammate_ids: ["tea_123"] },
    call: (front) => front.teammateGroups.removeTeammates("tmg_123", { teammate_ids: ["tea_123"] }),
    method: "DELETE",
    name: "teammateGroups.removeTeammates",
    path: "/teammate_groups/tmg_123/teammates",
    status: 204,
  },
  {
    call: (front) => front.teammateGroups.listTeams("tmg_123"),
    method: "GET",
    name: "teammateGroups.listTeams",
    path: "/teammate_groups/tmg_123/teams",
    response: { _results: [] },
    status: 200,
  },
  {
    body: { team_ids: ["tim_123"] },
    call: (front) => front.teammateGroups.addTeams("tmg_123", { team_ids: ["tim_123"] }),
    method: "POST",
    name: "teammateGroups.addTeams",
    path: "/teammate_groups/tmg_123/teams",
    status: 204,
  },
  {
    body: { team_ids: ["tim_123"] },
    call: (front) => front.teammateGroups.removeTeams("tmg_123", { team_ids: ["tim_123"] }),
    method: "DELETE",
    name: "teammateGroups.removeTeams",
    path: "/teammate_groups/tmg_123/teams",
    status: 204,
  },
  {
    call: (front) => front.teams.listTeams(),
    method: "GET",
    name: "teams.listTeams",
    path: "/teams",
    response: { _results: [] },
    status: 200,
  },
  {
    call: (front) => front.teams.getTeam("tim_123"),
    method: "GET",
    name: "teams.getTeam",
    path: "/teams/tim_123",
    response: {
      _links: {},
      id: "tim_123",
      inboxes: [{}],
      members: [
        {
          _links: {},
          custom_fields: {},
          email: "person@example.com",
          first_name: "Example",
          id: "tea_123",
          is_admin: false,
          is_available: false,
          is_blocked: false,
          last_name: "Example",
          type: "user",
          username: "Example",
        },
      ],
      name: "Example",
    },
    status: 200,
  },
  {
    body: { teammate_ids: ["tea_123"] },
    call: (front) => front.teams.addTeammates("tim_123", { teammate_ids: ["tea_123"] }),
    method: "POST",
    name: "teams.addTeammates",
    path: "/teams/tim_123/teammates",
    status: 204,
  },
  {
    body: { teammate_ids: ["tea_123"] },
    call: (front) => front.teams.removeTeammates("tim_123", { teammate_ids: ["tea_123"] }),
    method: "DELETE",
    name: "teams.removeTeammates",
    path: "/teams/tim_123/teammates",
    status: 204,
  },
  {
    call: (front) => front.teams.listChannels("tim_123"),
    method: "GET",
    name: "teams.listChannels",
    path: "/teams/tim_123/channels",
    response: { _results: [] },
    status: 200,
  },
  {
    call: (front) => front.teams.listContactLists("tim_123"),
    method: "GET",
    name: "teams.listContactLists",
    path: "/teams/tim_123/contact_lists",
    response: { _results: [] },
    status: 200,
  },
  {
    body: { name: "Example" },
    call: (front) => front.teams.createContactList("tim_123", { name: "Example" }),
    method: "POST",
    name: "teams.createContactList",
    path: "/teams/tim_123/contact_lists",
    status: 204,
  },
  {
    call: (front) =>
      front.teams.listContacts("tim_123", {
        limit: 1,
        page_token: PAGE_TOKEN,
        q: "Example",
        sort_by: "created_at",
        sort_order: "asc",
      }),
    method: "GET",
    name: "teams.listContacts",
    path: `/teams/tim_123/contacts?limit=1&page_token=${PAGE_TOKEN}&q=Example&sort_by=created_at&sort_order=asc`,
    response: { _results: [] },
    status: 200,
  },
  {
    body: { handles: [{ handle: "person@example.com", source: "email" }] },
    call: (front) =>
      front.teams.createContact("tim_123", {
        handles: [{ handle: "person@example.com", source: "email" }],
      }),
    method: "POST",
    name: "teams.createContact",
    path: "/teams/tim_123/contacts",
    response: {},
    status: 201,
  },
  {
    call: (front) => front.teams.listInboxes("tim_123"),
    method: "GET",
    name: "teams.listInboxes",
    path: "/teams/tim_123/inboxes",
    response: { _results: [] },
    status: 200,
  },
  {
    call: (front) =>
      front.teams.listMessageTemplateFolders("tim_123", {
        sort_by: "created_at",
        sort_order: "asc",
      }),
    method: "GET",
    name: "teams.listMessageTemplateFolders",
    path: "/teams/tim_123/message_template_folders?sort_by=created_at&sort_order=asc",
    response: { _results: [] },
    status: 200,
  },
  {
    body: { name: "Example" },
    call: (front) => front.teams.createMessageTemplateFolder("tim_123", { name: "Example" }),
    method: "POST",
    name: "teams.createMessageTemplateFolder",
    path: "/teams/tim_123/message_template_folders",
    response: { _links: {}, id: "fld_123", name: "Example" },
    status: 201,
  },
  {
    call: (front) =>
      front.teams.listMessageTemplates("tim_123", { sort_by: "created_at", sort_order: "asc" }),
    method: "GET",
    name: "teams.listMessageTemplates",
    path: "/teams/tim_123/message_templates?sort_by=created_at&sort_order=asc",
    response: { _results: [] },
    status: 200,
  },
  {
    body: { body: "Example", name: "Example" },
    call: (front) =>
      front.teams.createMessageTemplate("tim_123", { body: "Example", name: "Example" }),
    method: "POST",
    name: "teams.createMessageTemplate",
    path: "/teams/tim_123/message_templates",
    response: {
      _links: {},
      attachments: [
        {
          content_type: "Example",
          filename: "Example",
          id: "rsp_123",
          metadata: {},
          size: 1,
          url: "Example",
        },
      ],
      body: "Example",
      id: "rsp_123",
      inbox_ids: ["inb_123"],
      is_available_for_all_inboxes: false,
      name: "Example",
      subject: "Example",
    },
    status: 201,
  },
  {
    call: (front) => front.teams.listRules("tim_123"),
    method: "GET",
    name: "teams.listRules",
    path: "/teams/tim_123/rules",
    response: { _results: [] },
    status: 200,
  },
  {
    call: (front) => front.teams.listShifts("tim_123"),
    method: "GET",
    name: "teams.listShifts",
    path: "/teams/tim_123/shifts",
    response: { _results: [] },
    status: 200,
  },
  {
    body: {
      color: "black",
      name: "Example",
      teammate_ids: ["tea_123"],
      times: {},
      timezone: "Example",
    },
    call: (front) =>
      front.teams.createShift("tim_123", {
        color: "black",
        name: "Example",
        teammate_ids: ["tea_123"],
        times: {},
        timezone: "Example",
      }),
    method: "POST",
    name: "teams.createShift",
    path: "/teams/tim_123/shifts",
    response: {
      _links: {},
      color: "black",
      id: "shf_123",
      name: "Example",
      times: {},
      timezone: "Example",
    },
    status: 201,
  },
  {
    call: (front) => front.teams.listSignatures("tim_123"),
    method: "GET",
    name: "teams.listSignatures",
    path: "/teams/tim_123/signatures",
    response: { _results: [] },
    status: 200,
  },
  {
    body: { body: "Example", is_default: false, name: "Example" },
    call: (front) =>
      front.teams.createSignature("tim_123", {
        body: "Example",
        is_default: false,
        name: "Example",
      }),
    method: "POST",
    name: "teams.createSignature",
    path: "/teams/tim_123/signatures",
    response: {
      _links: {},
      body: "Example",
      channel_ids: ["cha_123"],
      id: "sig_123",
      is_default: false,
      is_private: false,
      is_visible_for_all_teammate_channels: false,
      name: "Example",
      sender_info: "Example",
    },
    status: 201,
  },
  {
    call: (front) =>
      front.teams.listTags("tim_123", {
        limit: 1,
        page_token: PAGE_TOKEN,
        sort_by: "created_at",
        sort_order: "asc",
      }),
    method: "GET",
    name: "teams.listTags",
    path: `/teams/tim_123/tags?limit=1&page_token=${PAGE_TOKEN}&sort_by=created_at&sort_order=asc`,
    response: { _results: [] },
    status: 200,
  },
  {
    body: { is_visible_in_conversation_lists: true, name: "Example" },
    call: (front) =>
      front.teams.createTag("tim_123", { is_visible_in_conversation_lists: true, name: "Example" }),
    method: "POST",
    name: "teams.createTag",
    path: "/teams/tim_123/tags",
    response: {
      _links: {},
      description: "Example",
      highlight: "Example",
      id: "tag_123",
      is_private: false,
      is_visible_in_conversation_lists: false,
      name: "Example",
    },
    status: 201,
  },
  {
    call: (front) => front.teams.listViews("tim_123", { limit: 1, page_token: PAGE_TOKEN }),
    method: "GET",
    name: "teams.listViews",
    path: `/teams/tim_123/views?limit=1&page_token=${PAGE_TOKEN}`,
    response: { _results: [] },
    status: 200,
  },
  {
    body: { inbox_ids: ["inb_123"], name: "Example" },
    call: (front) => front.teams.createView("tim_123", { inbox_ids: ["inb_123"], name: "Example" }),
    method: "POST",
    name: "teams.createView",
    path: "/teams/tim_123/views",
    response: {
      _links: {},
      assignee_ids: ["viw_123"],
      highlight: "Example",
      id: "viw_123",
      inbox_ids: ["inb_123"],
      name: "Example",
      no_tags: false,
      not_assignee_ids: ["viw_123"],
      not_tag_ids: ["viw_123"],
      tag_ids: ["tag_123"],
    },
    status: 201,
  },
  {
    call: (front) => front.teammates.list(),
    method: "GET",
    name: "teammates.list",
    path: "/teammates",
    response: { _results: [] },
    status: 200,
  },
  {
    call: (front) => front.teammates.get("tea_123"),
    method: "GET",
    name: "teammates.get",
    path: "/teammates/tea_123",
    response: {
      _links: {},
      custom_fields: {},
      email: "person@example.com",
      first_name: "Example",
      id: "tea_123",
      is_admin: false,
      is_available: false,
      is_blocked: false,
      last_name: "Example",
      type: "user",
      username: "Example",
    },
    status: 200,
  },
  {
    body: {},
    call: (front) => front.teammates.update("tea_123", {}),
    method: "PATCH",
    name: "teammates.update",
    path: "/teammates/tea_123",
    status: 204,
  },
  {
    call: (front) => front.teammates.listCustomFields(),
    method: "GET",
    name: "teammates.listCustomFields",
    path: "/teammates/custom_fields",
    response: { _results: [] },
    status: 200,
  },
  {
    call: (front) =>
      front.teammates.listAssignedConversations("tea_123", {
        limit: 1,
        page_token: PAGE_TOKEN,
        q: "Example",
      }),
    method: "GET",
    name: "teammates.listAssignedConversations",
    path: `/teammates/tea_123/conversations?limit=1&page_token=${PAGE_TOKEN}&q=Example`,
    response: { _results: [] },
    status: 200,
  },
  {
    call: (front) => front.teammates.listChannels("tea_123"),
    method: "GET",
    name: "teammates.listChannels",
    path: "/teammates/tea_123/channels",
    response: { _results: [] },
    status: 200,
  },
  {
    call: (front) => front.teammates.listContactLists("tea_123"),
    method: "GET",
    name: "teammates.listContactLists",
    path: "/teammates/tea_123/contact_lists",
    response: { _results: [] },
    status: 200,
  },
  {
    body: { name: "Example" },
    call: (front) => front.teammates.createContactList("tea_123", { name: "Example" }),
    method: "POST",
    name: "teammates.createContactList",
    path: "/teammates/tea_123/contact_lists",
    status: 204,
  },
  {
    call: (front) =>
      front.teammates.listContacts("tea_123", {
        limit: 1,
        page_token: PAGE_TOKEN,
        q: "Example",
        sort_by: "created_at",
        sort_order: "asc",
      }),
    method: "GET",
    name: "teammates.listContacts",
    path: `/teammates/tea_123/contacts?limit=1&page_token=${PAGE_TOKEN}&q=Example&sort_by=created_at&sort_order=asc`,
    response: { _results: [] },
    status: 200,
  },
  {
    body: { handles: [{ handle: "person@example.com", source: "email" }] },
    call: (front) =>
      front.teammates.createContact("tea_123", {
        handles: [{ handle: "person@example.com", source: "email" }],
      }),
    method: "POST",
    name: "teammates.createContact",
    path: "/teammates/tea_123/contacts",
    response: {},
    status: 201,
  },
  {
    call: (front) =>
      front.teammates.listMessageTemplateFolders("tea_123", {
        sort_by: "created_at",
        sort_order: "asc",
      }),
    method: "GET",
    name: "teammates.listMessageTemplateFolders",
    path: "/teammates/tea_123/message_template_folders?sort_by=created_at&sort_order=asc",
    response: { _results: [] },
    status: 200,
  },
  {
    body: { name: "Example" },
    call: (front) => front.teammates.createMessageTemplateFolder("tea_123", { name: "Example" }),
    method: "POST",
    name: "teammates.createMessageTemplateFolder",
    path: "/teammates/tea_123/message_template_folders",
    response: { _links: {}, id: "fld_123", name: "Example" },
    status: 201,
  },
  {
    call: (front) =>
      front.teammates.listMessageTemplates("tea_123", { sort_by: "created_at", sort_order: "asc" }),
    method: "GET",
    name: "teammates.listMessageTemplates",
    path: "/teammates/tea_123/message_templates?sort_by=created_at&sort_order=asc",
    response: { _results: [] },
    status: 200,
  },
  {
    body: { body: "Example", name: "Example" },
    call: (front) =>
      front.teammates.createMessageTemplate("tea_123", { body: "Example", name: "Example" }),
    method: "POST",
    name: "teammates.createMessageTemplate",
    path: "/teammates/tea_123/message_templates",
    response: {
      _links: {},
      attachments: [
        {
          content_type: "Example",
          filename: "Example",
          id: "rsp_123",
          metadata: {},
          size: 1,
          url: "Example",
        },
      ],
      body: "Example",
      id: "rsp_123",
      inbox_ids: ["inb_123"],
      is_available_for_all_inboxes: false,
      name: "Example",
      subject: "Example",
    },
    status: 201,
  },
  {
    call: (front) => front.teammates.listRules("tea_123"),
    method: "GET",
    name: "teammates.listRules",
    path: "/teammates/tea_123/rules",
    response: { _results: [] },
    status: 200,
  },
  {
    call: (front) => front.teammates.listShifts("tea_123"),
    method: "GET",
    name: "teammates.listShifts",
    path: "/teammates/tea_123/shifts",
    response: { _results: [] },
    status: 200,
  },
  {
    call: (front) => front.teammates.listSignatures("tea_123"),
    method: "GET",
    name: "teammates.listSignatures",
    path: "/teammates/tea_123/signatures",
    response: { _results: [] },
    status: 200,
  },
  {
    body: { body: "Example", is_default: false, name: "Example" },
    call: (front) =>
      front.teammates.createSignature("tea_123", {
        body: "Example",
        is_default: false,
        name: "Example",
      }),
    method: "POST",
    name: "teammates.createSignature",
    path: "/teammates/tea_123/signatures",
    response: {
      _links: {},
      body: "Example",
      channel_ids: ["cha_123"],
      id: "sig_123",
      is_default: false,
      is_private: false,
      is_visible_for_all_teammate_channels: false,
      name: "Example",
      sender_info: "Example",
    },
    status: 201,
  },
  {
    call: (front) =>
      front.teammates.listTags("tea_123", {
        limit: 1,
        page_token: PAGE_TOKEN,
        sort_by: "created_at",
        sort_order: "asc",
      }),
    method: "GET",
    name: "teammates.listTags",
    path: `/teammates/tea_123/tags?limit=1&page_token=${PAGE_TOKEN}&sort_by=created_at&sort_order=asc`,
    response: { _results: [] },
    status: 200,
  },
  {
    body: { is_visible_in_conversation_lists: true, name: "Example" },
    call: (front) =>
      front.teammates.createTag("tea_123", {
        is_visible_in_conversation_lists: true,
        name: "Example",
      }),
    method: "POST",
    name: "teammates.createTag",
    path: "/teammates/tea_123/tags",
    response: {
      _links: {},
      description: "Example",
      highlight: "Example",
      id: "tag_123",
      is_private: false,
      is_visible_in_conversation_lists: false,
      name: "Example",
    },
    status: 201,
  },
  {
    body: { name: "Example" },
    call: (front) => front.teams.createInbox("tim_123", { name: "Example" }),
    method: "POST",
    name: "teams.createInbox",
    path: "/teams/tim_123/inboxes",
    response: {},
    status: 201,
  },
];

test.each(cases)("$name sends the endpoint request and returns its response", async (endpoint) => {
  const { front, requests } = createMockClient(() => {
    if (endpoint.raw) {
      return new Response(new Uint8Array([1, 2, 3]));
    }
    if (endpoint.status === 204) {
      return new Response(null, { status: 204 });
    }
    return jsonResponse(endpoint.response, { status: endpoint.status });
  });
  const result = await endpoint.call(front);
  expect(requests).toHaveLength(1);
  expect(requests[0]?.method).toBe(endpoint.method);
  expect(requests[0]?.url).toBe(`https://api2.frontapp.com${endpoint.path}`);
  if (endpoint.body === undefined) {
    expect(await requests[0]?.text()).toBe("");
  } else {
    expect(await requests[0]?.json()).toEqual(endpoint.body);
  }
  if (endpoint.raw) {
    expect(result).toBeInstanceOf(Response);
    if (result instanceof Response) {
      expect(new Uint8Array(await result.arrayBuffer())).toEqual(new Uint8Array([1, 2, 3]));
    } else {
      throw new TypeError("Expected a raw Response");
    }
  } else {
    expect(endpoint.response).toEqual(result);
  }
});

const optionalBodyCases = [
  {
    call: (front: Front) => front.accounts.removeContacts("acc_123"),
    name: "accounts.removeContacts",
  },
  {
    call: (front: Front) => front.contactLists.removeContacts("ctl_123"),
    name: "contactLists.removeContacts",
  },
  { call: (front: Front) => front.contacts.deleteHandle("ctc_123"), name: "contacts.deleteHandle" },
  {
    call: (front: Front) => front.conversations.deleteFollowers("cnv_123"),
    name: "conversations.deleteFollowers",
  },
  {
    call: (front: Front) => front.conversations.removeLinks("cnv_123"),
    name: "conversations.removeLinks",
  },
  {
    call: (front: Front) => front.conversations.removeTag("cnv_123"),
    name: "conversations.removeTag",
  },
  { call: (front: Front) => front.drafts.delete("msg_123"), name: "drafts.delete" },
  {
    call: (front: Front) => front.inboxes.removeTeammateAccess("inb_123"),
    name: "inboxes.removeTeammateAccess",
  },
  {
    call: (front: Front) => front.shifts.removeTeammates("shf_123"),
    name: "shifts.removeTeammates",
  },
  {
    call: (front: Front) => front.teammateGroups.removeInboxes("tmg_123"),
    name: "teammateGroups.removeInboxes",
  },
  {
    call: (front: Front) => front.teammateGroups.removeTeammates("tmg_123"),
    name: "teammateGroups.removeTeammates",
  },
  {
    call: (front: Front) => front.teammateGroups.removeTeams("tmg_123"),
    name: "teammateGroups.removeTeams",
  },
  { call: (front: Front) => front.teams.removeTeammates("tim_123"), name: "teams.removeTeammates" },
];

test.each(optionalBodyCases)("$name accepts an omitted optional request body", async (endpoint) => {
  const { front, requests } = createMockClient(() => new Response(null, { status: 204 }));
  expect(await endpoint.call(front)).toBeUndefined();
  expect(requests).toHaveLength(1);
  expect(await requests[0]?.text()).toBe("");
});
